routes/web.php
<?php

use App\Http\Controllers\DishController;
use App\Http\Controllers\InstitutionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\InstitutionController as AdminInstitutionsController;
use App\Http\Controllers\Admin\DishController as AdminDishesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [InstitutionController::class, 'index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('institutions', InstitutionController::class)->only(['index', 'show']);
Route::resource('dishes', DishController::class)->only(['index', 'show']);
Route::post('dishes/addDish', [DishController::class, 'addDish'])->name('dishes.addDish');
Route::delete('dishes/removeDish', [DishController::class, 'removeDish'])->name('dishes.removeDish');


Route::prefix('admin')->name('admin.')->group(function (){
    Route::resources([
        'institutions' => AdminInstitutionsController::class,
        'dishes' => AdminDishesController::class,
    ]);
});

app/Models/Institution.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property mixed name
 */
class Institution extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'content', 'picture'];

    /**
     * @return HasMany
     */
    public function dishes(): HasMany
    {
        return $this->hasMany(Dish::class);
    }
}

app/Http/Controllers/Admin/InstitutionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\InstitutionRequest;
use App\Models\Institution;
use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;

class InstitutionController extends Controller
{


    /**
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function index()
    {
        $this->authorize('viewAny', User::class);
        $institutions = Institution::all();
        return view('admin.institutions.index', compact('institutions'));
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        $this->authorize('viewAny', User::class);
        return view('admin.institutions.create');
    }

    /**
     * @param InstitutionRequest $request
     * @return Application|Redirector|RedirectResponse
     */
    public function store(InstitutionRequest $request)
    {
        $this->authorize('viewAny', User::class);
        $data = $request->all();
        $file = $request->file('picture');
        if (!is_null($file)){
            $path = $file->store('institutions', 'public');
            $data['picture']= $path;
            $data['picture_name'] = $request->file('picture')->getClientOriginalName();
        }
        $institution = new Institution($data);
        $institution->save();

        return redirect(route('admin.institutions.index'))->with('success',
            "Institution $institution->name has been successfully stored!");
    }

    /**
     * @param Institution $institution
     * @return Application|Factory|View
     */
    public function show(Institution $institution)
    {
        $this->authorize('viewAny', User::class);
        $institution->setRelation('dishes', $institution->dishes()->simplePaginate(2));
        return view('admin.institutions.show', compact('institution'));
    }

    /**
     * @param Institution $institution
     * @return Application|Factory|View
     */
    public function edit(Institution $institution)
    {
        $this->authorize('viewAny', User::class);
        return view('admin.institutions.edit', compact('institution'));
    }

    /**
     * @param InstitutionRequest $request
     * @param Institution $institution
     * @return Application|Redirector|RedirectResponse
     */
    public function update(InstitutionRequest $request, Institution $institution)
    {
        $this->authorize('viewAny', User::class);
        $data = $request->all();
        $file = $request->file('picture');
        if (!is_null($file)){
            $path = $file->store('institutions', 'public');
            $data['picture']= $path;
            $data['picture_name'] = $request->file('picture')->getClientOriginalName();
        }
        $institution->update($data);

        return redirect(route('admin.institutions.show', compact('institution')))->with('success',
            "Institution $institution->name has been successfully updated!");
    }

    /**
     * @param Institution $institution
     * @return Application|Redirector|RedirectResponse
     */
    public function destroy(Institution $institution)
    {
        $this->authorize('viewAny', User::class);
        $institution->delete();
        return redirect(route('admin.institutions.index'))->with('success',
            "Establishment $institution->name has been successfully deleted!");
    }
}

app/Http/Controllers/InstitutionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Institution;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class InstitutionController extends Controller
{

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        if (Auth::user()){
            if (!session()->exists('institutions')){
                session()->put('institutions', []);
            }
        }
        $institutions = Institution::all();
        return view('institutions.index', compact('institutions'));
    }


    /**
     * @param Institution $institution
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(Institution $institution)
    {
        return view('institutions.show', compact('institution'));
    }




}

resources/views/admin/institutions/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row mt-4 mb-3">
            <h1>Добавить новое заведении</h1>
        </div>
        <form enctype="multipart/form-data" method="post" action="{{route('admin.institutions.store')}}">
            @csrf
            <div class="mb-3">
                <label for="name">Название заведения: </label>
                <input type="text" class="form-control  @error('name') is-invalid @enderror" id="name" name="name" value=" {{old('name')}}">
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="content">Подробнее о заведении: </label>
                <textarea class="form-control  @error('content') is-invalid @enderror" rows="10" cols="30"
                          name="content" id="content" >
                        {{old('content')}}
                    </textarea>
                @error('content')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="picture" class=" col-form-label">Фото: </label>
                <div class="custom-file form-control" >
                    <input type="file" class="custom-file-input @error('picture') is-invalid @enderror "
                           id="picture" name="picture" value="{{old('picture')}}">
                    <label class="custom-file-label" for="customFile">Выберите фотографию</label>
                    @error('picture')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <hr class="border-dark-sm">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
@endsection

resources/views/admin/institutions/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row mt-4 mb-3">
            <h1>Редактировать данные о заведении</h1>
        </div>
        <form enctype="multipart/form-data" method="post" action="{{route('admin.institutions.update',['institution'=> $institution])}}">
            @method('put')
            @csrf
            <div class="mb-3">
                <label for="name">Название заведения: </label>
                <input type="text" class="form-control  @error('name') is-invalid @enderror" id="name" name="name"
                       value=" {{$institution->name}}">
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="content">Подробнее о заведении: </label>
                <textarea class="form-control  @error('content') is-invalid @enderror" rows="10" cols="30"
                          name="content" id="content" >
                        {{$institution->content}}
                    </textarea>
                @error('content')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="picture" class=" col-form-label">Фото: </label>
                <div class="mb-3 row">
                    <img src="{{asset('/storage/'. $institution->picture)}}"
                         alt="{{$institution->picture}}" class="w-30 h-50 mr-3">
                </div>
                <div class="custom-file form-control" >
                    <input type="file" class="custom-file-input @error('picture') is-invalid @enderror "
                           id="picture" name="picture" value="{{$institution->picture}}">
                    <label class="custom-file-label" for="customFile">Выберите фотографию</label>
                    @error('picture')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <hr class="border-dark-sm">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
@endsection

resources/views/admin/institutions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row pt-5">
            <div class="col">
                <a  class="btn btn-sm" href="{{route('admin.institutions.create')}}"
                    style="background-color: burlywood; color: whitesmoke">
                    <h5>Добавить новое заведение</h5>
                </a>
            </div>
        </div>
        <div class="container-sm mt-5">
            <table class="table">
                <thead style="color: #5d561b">
                <tr>
                    <th scope="col"><h4>Наименование заведений</h4></th>
                    <th scope="col"><h4>Действие</h4></th>
                </tr>
                </thead>
                <tbody>
                @foreach($institutions as $institution)
                    <tr>
                        <th scope="row">
                            <a style="color: #4c110f" href="{{route('admin.institutions.show',['institution'=> $institution])}}">
                                {{$institution->name}}
                            </a>
                        </th>
                        <td>
                            <a class="btn btn-sm" href="{{route('admin.institutions.edit', ['institution' => $institution])}}">
                                <button class="btn btn btn-sm btn-primary" type="submit">Update</button>
                            </a>
                            <a class="btn btn-sm" >
                                <form method="POST" action="{{route('admin.institutions.destroy', ['institution'=> $institution])}}">
                                    @method('delete')
                                    @csrf
                                    <button class="btn btn btn-sm btn-danger" type="submit">Delete</button>
                                </form>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/institutions/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-sm">
        <div class="institution-block">
            <h3 class="mb-4 mt-4 text-danger text-center">{{$institution->name}}</h3>
            <div class="row ">
                <div class="col-12 col-md-6 pr-5 ">
                    <p class="mt-4 ml-2 mb-4 mr-2 text-center">{{$institution->content}}</p>
                </div>
                <div class="col-12 col-md-6">
                    <img src="{{asset('/storage/'. $institution->picture)}}"
                         alt="{{$institution->picture_name}}" class="w-30 h-50 mr-3">
                </div>
            </div>
        </div>
        <hr>
        <div class="container-sm">
            <h3 class="mb-5 mt-5 text-center">Блюда</h3>
            @foreach($institution->dishes as $dish)
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 justify-content-center pb-5">
                    <div class="col pr-5">
                        <a href="{{route('admin.dishes.show', ['dish'=> $dish])}}">
                            <p><b>{{$dish->name}}</b></p>
                        </a>
                    </div>
                    <div class="col">
                        <p>{{$dish->content}}</p>
                    </div>
                    <div class="col">
                        <img src="{{asset('/storage/'.$dish->picture)}}" alt="{{$dish->picture_name}}">
                    </div>
                </div>
            @endforeach
            <div class="row">
                <div class="col-md-auto">
                    {{$institution->dishes->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection