routes/web.php
<?php

use App\Http\Controllers\DishController;
use App\Http\Controllers\InstitutionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\InstitutionController as AdminInstitutionsController;
use App\Http\Controllers\Admin\DishController as AdminDishesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [InstitutionController::class, 'index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('institutions', InstitutionController::class)->only(['index', 'show']);
Route::resource('dishes', DishController::class)->only(['index', 'show']);
Route::post('dishes/addDish', [DishController::class, 'addDish'])->name('dishes.addDish');
Route::delete('dishes/removeDish', [DishController::class, 'removeDish'])->name('dishes.removeDish');


Route::prefix('admin')->name('admin.')->group(function (){
    Route::resources([
        'institutions' => AdminInstitutionsController::class,
        'dishes' => AdminDishesController::class,
    ]);
});

app/Models/Dish.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @method static paginate(int $int)
 * @property mixed name
 */
class Dish extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'content', 'price', 'picture', 'institution_id'];

    /**
     * @return BelongsTo
     */
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }
}

app/Http/Controllers/Admin/DishController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\DishRequest;
use App\Models\Dish;
use App\Models\Institution;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;

class DishController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $this->authorize('viewAny', User::class);
        $dishes = Dish::paginate(6);
        return view('admin.dishes.index', compact('dishes'));
    }


    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        $this->authorize('viewAny', User::class);
        $institutions = Institution::all();
        return view('admin.dishes.create', compact('institutions'));
    }


    /**
     * @param DishRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(DishRequest $request)
    {
        $this->authorize('viewAny', User::class);
        $data = $request->all();
        $file = $request->file('picture');
        if (!is_null($file))
        {
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
            $data['picture_name'] = $request->file('picture')->getClientOriginalName();
        }

        $dish = new Dish($data);
        $dish->save();

        return redirect(route('admin.dishes.index'))->with('success',
            "Блюдо $dish->name успешно обновлено!");
    }


    /**
     * @param Dish $dish
     * @return Application|Factory|View
     */
    public function show(Dish $dish)
    {
        $this->authorize('viewAny', User::class);
        $institutions = Institution::all();
//        $dish->setRelation('establishment', $dish->establishment()->simplePaginate(2));
        return view('admin.dishes.show', compact('dish', 'institutions'));
    }


    /**
     * @param Dish $dish
     * @return Application|Factory|View
     */
    public function edit(Dish $dish)
    {
        $this->authorize('viewAny', User::class);
        $institutions = Institution::all();
        return view('admin.dishes.edit', compact('dish', 'institutions'));
    }


    /**
     * @param DishRequest $request
     * @param Dish $dish
     * @return Application|Redirector|RedirectResponse
     */
    public function update(DishRequest $request, Dish $dish)
    {
        $this->authorize('viewAny', User::class);
        $data = $request->all();
        $file = $request->file('picture');
        if (!is_null($file))
        {
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
            $data['picture_name'] = $request->file('picture')->getClientOriginalName();
        }

        $dish->update($data);
        return redirect(route('admin.dishes.show', compact('dish')))->with('success',
            "Блюдо $dish->name успешно обновлено!");
    }


    /**
     * @param Dish $dish
     * @return Application|Redirector|RedirectResponse
     */
    public function destroy(Dish $dish)
    {
        $this->authorize('viewAny', User::class);
        $dish->delete();
        return redirect()->back()->with('success',
            "Блюдо $dish->name успешно удалено!");

    }
}

app/Http/Controllers/DishController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dish;
use Illuminate\Http\Request;

class DishController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth'])->only(['addDish']);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $dishes = Dish::all();
        return view('dishes.index', compact('dishes'));
    }


    /**
     * @param Dish $dish
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(Dish $dish)
    {
        return view('dishes.show', compact('dish'));
    }

    public function addDish(Request $request)
    {
        $dish = Dish::find($request->input('dish_id'));
        $institution = $dish->institution_id;
        if (session()->exists("institutions.$institution.$dish->id")){
            $count = session()->get("institutions.$institution.$dish->id.count") + 1;
            session()->put("institutions.$institution.$dish->id.count",$count );
            $sum = 0;
            foreach (session()->get("institutions.$institution") as $dish) {
                if (!is_int($dish)){
                    $total = $dish['price'] * $dish['count'];
                    $sum += $total;
                }
            }
            session()->put("institutions.$institution.sum", $sum );
        }else {
            session()->put("institutions.$institution.$dish->id");
            session()->put("institutions.$institution.$dish->id.id", $dish->id);
            session()->put("institutions.$institution.$dish->id.name", $dish->name);
            session()->put("institutions.$institution.$dish->id.price", $dish->price);
            session()->put("institutions.$institution.$dish->id.count", 1);
            $sum = 0;
            foreach (session()->get("institutions.$institution") as $dish) {
                if (!is_int($dish)){
                    $sum += $dish['price'] * $dish['count'];
                }
            }
            session()->put("institutions.$institution.sum", $sum );
        }
        return redirect()->back();

    }

    public function removeDish(Request $request)
    {
        $dish = Dish::find($request->input('dish_id'));
        $institution = $dish->institution_id;

        if (1 >= session()->get("institutions.$institution.$dish->id.count")) {
            $sum = session()->get("institutions.$institution.sum") - session()->get("institutions.$institution.$dish->id.price");
            session()->put("institutions.$institution.sum", $sum );
            session()->remove("institutions.$institution.$dish->id");
            return redirect()->back();
        }

        if (session()->get("institutions.$institution.$dish->id.count") > 1) {
            $sum = session()->get("institutions.$institution.sum") - session()->get("institutions.$institution.$dish->id.price");
            session()->put("institutions.$institution.sum", $sum );
            $count = session()->get("institutions.$institution.$dish->id.count") - 1;
            session()->put("institutions.$institution.$dish->id.count", $count);
            return redirect()->back();
        }
    }
}

resources/views/admin/dishes/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">

        <form enctype="multipart/form-data" method="post" action="{{route('admin.dishes.store')}}">
            @csrf
            <div class="form-group row mt-5">
                <label for="name" class="col-sm-2 col-form-label ">Название блюда</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                           value="{{old('name')}}"/>
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="content" class="col-sm-2 col-form-label">Описание</label>
                <div class="col-sm-5">
                    <textarea class="form-control  @error('content') is-invalid @enderror" rows="10"  cols="30" name="content" id="content" >
                        {{old('content')}}
                    </textarea>
                    @error('content')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="price" class="col-sm-2 col-form-label">Цена</label>
                <div class="col-sm-5">
                    <input type="number" class="form-control  @error('price') is-invalid @enderror" name="price" id="price"/>
                    @error('price')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="establishment_id" class="col-sm-2 col-form-label">Название заведения</label>
                <div class="col-sm-5">
                    <select class="custom-select  @error('institution_id') is-invalid @enderror " name="institution_id">
                        @foreach($institutions as $institution)
                            <option value=""></option>
                            <option value="{{$institution->id}}">{{$institution->name}}</option>
                        @endforeach
                    </select>
                    @error('institution_id')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="picture" class="col-sm-2 col-form-label">Фото</label>
                <div class="custom-file col-sm-5" >
                    <input type="file" class=" custom-file-input @error('picture') is-invalid @enderror " id="picture" name="picture">
                    <label class="custom-file-label" for="customFile">Выберите картинку</label>
                    @error('picture')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <hr class="border-dark-sm">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
@endsection

resources/views/admin/dishes/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Редактировать блюдо</h1>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <form enctype="multipart/form-data" method="post" action="{{route('admin.dishes.update',['dish' => $dish])}}">
                    @method('put')
                    @csrf
                    <div class="form-group">
                        <label for="name">Наименование: </label>
                        <input name="name" type="text" class="form-control @error('name') is-invalid @enderror" value="{{$dish->name}}" id="name">
                    </div>
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <div class="form-group">
                        <label for="price">Цена: </label>
                        <input name="price" type="number" value="{{$dish->price}}" class="form-control @error('price') is-invalid @enderror" id="price">
                    </div>
                    @error('price')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <div class="form-group">
                        <label for="exampleInputPassword1">О блюде: </label>
                        <textarea name="content" class="form-control @error('content') is-invalid @enderror" id="exampleInputPassword1">{{$dish->content}}</textarea>
                    </div>
                    @error('content')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <div class="form-group"><label class="col-sm-2 control-label">Заведение:</label>
                        <select class="custom-select" name="institution_id">
                            @foreach($institutions as $institution)
                                <option @if($dish->institution->id == $institution->id) selected @endif value="{{$institution->id}}">{{$institution->name}}</option>
                            @endforeach
                        </select>
                        @error('institution_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <div class="custom-file">
                            <img style="height: 150px; width: 150px;" src="{{asset('/storage/' . $dish->picture)}}" class="card-img-top" alt="{{$dish->picture_name}}">
                            <input type="file" value="{{$dish->picture}}" class="custom-file-input @error('picture') is-invalid @enderror " id="customFile" name="picture">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                            @error('picture')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/dishes/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container ">
        <div class="row mt-5">
            <div class="col">
                <a  class="btn btn-sm" href="{{route('admin.dishes.create')}}" style="background-color: burlywood; color: whitesmoke">
                    <h5>Добавить новое блюдо</h5>
                </a>
            </div>
        </div>
        <div class="dishes-block">
            <h5 class="pt-4 text-center" >Все блюда: </h5>
            <hr>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                @foreach($dishes as $dish)
                    <div class="col mb-4">
                        <div class="card">
                            <div class="card-header">
                                <img class="card-img-top" src="{{asset('/storage/'. $dish->picture)}}"
                                     alt="{{$dish->picture}}">
                            </div>
                            <div class="card-body">
                                <p class="text-truncate text-center text-capitalize"><b>{{ $dish->name}}</b></p>
                                <blockquote class="blockquote mb-0">
                                    <form class="btn btn-sm position-center" method="post" action="{{route('admin.dishes.destroy', ['dish'=> $dish])}}">
                                        @method('delete')
                                        @csrf
                                        <button class="btn btn-sm btn-danger" type="submit">Удалить</button>
                                    </form>
                                    <a class="btn btn-sm" href="{{route('admin.dishes.edit', ['dish' => $dish])}}">
                                        <button class="btn btn btn-sm btn-primary" type="submit">Изменить</button>
                                    </a>
                                    <a class="btn btn-sm" href="{{route('admin.dishes.show', ['dish' => $dish])}}">
                                        <button class="btn btn btn-sm btn-success" type="submit">Подробнее</button>
                                    </a>
                                </blockquote>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="row">
            <div class="col-md-auto">
                {{$dishes->links('pagination::bootstrap-4')}}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/dishes/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-sm">
        <div class="dish-info-block ">
            <h3 class="mb-4 text-danger text-center mt-5">{{$dish->name}}</h3>
            <div class="row ">
                <div class="col-12 col-md-8 pr-5 ">
                    <p class="mt-4 ml-2 mb-4 mr-2">{{$dish->content}}</p>
                </div>
                <div class="col-12 col-md-4">
                    <img src="{{asset('/storage/'. $dish->picture)}}"
                         alt="{{$dish->picture_name}}" class="w-30 h-auto mr-3">
                </div>
            </div><br>
            <div class="row">
                <div class="col-12 col-md-8 pr-5 ">
                    <h5>Заведение:</h5>
                    <a href="{{route('admin.institutions.show', ['institution'=> $dish->institution->id])}}">
                        <p>
                            <b>{{$dish->institution->name}}</b>
                        </p>
                    </a>
                </div>
            </div>
        </div>
        <hr>
    </div>
@endsection